/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projetorestcomjakartaegradle;

import java.util.ArrayList;
import java.util.List;

import jakarta.ws.rs.ApplicationPath;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.core.Application;

@ApplicationPath("/api")
public class App extends Application {

	}
